### PR TITLE
Updated to 1.14.1

### PR DESCRIPTION
**Pull request by Shnupbups**

### CODE REVIEW

**Comment by TehNut** [comment]
Could you bump the version and add a new changelog section mentioning 1.14.1?

Also if you could test (add `options { debug = true }` to the CF block and run `gradlew curseforge`)  the CF upload and make sure it's pushing the proper jars, that'd be great.

**Comment by Shnupbups** [comment]
Is that good?

**Comment by Shnupbups** [comment]
I tried running `gradlew curseforge` but it gave me `CurseForge Project 291549 does not have an apiKey configured`.

**Comment by TehNut** [comment]
I think you can just set it to an empty string and it should work

**Comment by Shnupbups** [comment]
That didn't work either.

**Comment by TehNut** [comment]
fuck it we'll do it live

**Pull request merged**
